["fzf"]
type = "archive-file"
url = "https://github.com/junegunn/fzf/releases/download/0.53.0/fzf-0.53.0-linux_amd64.tar.gz"
path = "fzf"
refreshPeriod = "168h"

["lazygit"]
type = "archive-file"
url = "https://github.com/jesseduffield/lazygit/releases/download/v0.42.0/lazygit_0.42.0_Linux_x86_64.tar.gz"
path = "lazygit"
refreshPeriod = "168h"
