["fd"]
type = "archive-file"
url = "https://github.com/sharkdp/fd/releases/download/v10.1.0/fd-v10.1.0-x86_64-unknown-linux-musl.tar.gz"
stripComponents = 1
path = "fd"
executable = true

["fzf"]
type = "archive-file"
url = "https://github.com/junegunn/fzf/releases/download/0.53.0/fzf-0.53.0-linux_amd64.tar.gz"
path = "fzf"
executable = true

["git-credential-oauth"]
type = "archive-file"
url = "https://github.com/hickford/git-credential-oauth/releases/download/v0.13.2/git-credential-oauth_0.13.2_linux_amd64.tar.gz"
path = "git-credential-oauth"
executable = true

["lazygit"]
type = "archive-file"
url = "https://github.com/jesseduffield/lazygit/releases/download/v0.42.0/lazygit_0.42.0_Linux_x86_64.tar.gz"
path = "lazygit"
executable = true
