["ohmyzsh"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
exact = true
stripComponents = 1
exclude = ["*/omz", "*/custom", "*/cache", "*/*.md", "*/.*"]
refreshPeriod = "168h"
