["wallpapers/wallpaper.jpg"]
type = "file"
url = "https://bkt.reyma.dev/chezmoi/wallpaper.jpg"

["fonts/commit-mono"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/CommitMono.zip"
